In [1]:
#Continous integraion of latest data using https://github.com/swar/nba_api/blob/master/docs/examples/Finding%20Games.ipynb

In [1]:
import pandas as pd

C:\Users\BriacMarchandise\AppData\Local\Temp\ipykernel_31436\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
from nba_api.stats.static import teams

nba_teams = teams.get_teams()
# Select the dictionary for the Celtics, which contains their team ID
celtics = [team for team in nba_teams if team['abbreviation'] == 'BOS'][0]
celtics_id = celtics['id']

In [6]:
from nba_api.stats.endpoints import leaguegamefinder

# Query for games where the Celtics were playing
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=celtics_id)
# The first DataFrame of those returned is what we want.
games = gamefinder.get_data_frames()[0]
games.head()

TypeError: LeagueGameFinder.__init__() got an unexpected keyword argument 'team_id'

In [3]:
games.shape

NameError: name 'games' is not defined

In [10]:
games.groupby(games.SEASON_ID.str[-4:])[['GAME_ID']].count().loc['2015':]

           GAME_ID
SEASON_ID
2015           103
2016           115
2017           113
2018           101
2019           102
2020            80
2021           115
2022           111
2023            54

In [16]:
from nba_api.stats.endpoints import teamestimatedmetrics

# Query for games where the Celtics were playing
stat_team_finder = teamestimatedmetrics.TeamEstimatedMetrics(season = "2023-24")
# The first DataFrame of those returned is what we want.
stat_team = stat_team_finder.get_data_frames()[0]
stat_team

,TEAM_NAME,TEAM_ID,GP,W,L,W_PCT,MIN,E_OFF_RATING,E_DEF_RATING,E_NET_RATING,...,MIN_RANK,E_OFF_RATING_RANK,E_DEF_RATING_RANK,E_NET_RATING_RANK,E_AST_RATIO_RANK,E_OREB_PCT_RANK,E_DREB_PCT_RANK,E_REB_PCT_RANK,E_TM_TOV_PCT_RANK,E_PACE_RANK
0,Indiana Pacers,1610612754,50,27,23,0.540,2400.0,117.9,117.1,0.9,...,3,4,26,13,1,17,25,23,11,1
1,Washington Wizards,1610612764,48,9,39,0.188,2304.0,109.5,117.2,-7.7,...,22,25,27,26,8,30,30,30,12,1
2,Milwaukee Bucks,1610612749,48,32,16,0.667,2319.0,118.3,114.1,4.2,...,18,1,19,8,18,25,12,15,4,3
3,Atlanta Hawks,1610612737,48,21,27,0.438,2319.0,115.1,118.0,-2.9,...,18,12,28,23,28,3,24,16,14,4
4,San Antonio Spurs,1610612759,49,10,39,0.204,2362.0,107.6,116.0,-8.4,...,10,28,24,27,4,24,22,24,23,4
5,Los Angeles Lakers,1610612747,50,25,25,0.500,2420.0,111.5,112.6,-1.1,...,2,20,15,20,6,29,10,22,19,6
6,Detroit Pistons,1610612765,48,6,42,0.125,2314.0,109.3,118.4,-9.1,...,20,26,29,29,19,14,9,17,29,7
7,Dallas Mavericks,1610612742,48,26,22,0.542,2304.0,115.2,115.4,-0.1,...,22,9,23,17,21,23,28,29,2,8
8,Utah Jazz,1610612762,50,24,26,0.480,2425.0,113.1,116.1,-3.0,...,1,16,25,24,10,2,19,2,30,9
9,Oklahoma City Thunder,1610612760,49,34,15,0.694,2362.0,117.6,109.1,8.5,...,10,5,3,1,9,28,29,26,3,10
10,Sacramento Kings,1610612758,47,28,19,0.596,2281.0,114.3,114.1,0.2,...,24,14,17,16,5,19,1,13,13,11
11,Golden State Warriors,1610612744,45,21,24,0.467,2185.0,115.2,114.9,0.4,...,30,11,22,15,7,4,15,5,22,12
12,Memphis Grizzlies,1610612763,49,18,31,0.367,2362.0,104.9,110.8,-5.9,...,10,30,8,25,24,27,16,27,24,13
13,Philadelphia 76ers,1610612755,47,30,17,0.638,2266.0,116.7,111.0,5.6,...,26,6,11,5,25,13,26,20,1,14
14,Toronto Raptors,1610612761,48,17,31,0.354,2314.0,112.5,114.6,-2.1,...,20,19,21,22,3,15,18,18,16,14
15,Houston Rockets,1610612745,48,23,25,0.479,2329.0,111.3,109.7,1.6,...,17,23,6,12,23,20,5,12,7,16
16,New Orleans Pelicans,1610612740,49,28,21,0.571,2357.0,115.2,111.0,4.2,...,14,10,10,8,12,12,8,10,15,17
17,Portland Trail Blazers,1610612757,49,15,34,0.306,2377.0,106.0,114.6,-8.6,...,6,29,20,28,30,7,27,25,26,17
18,Orlando Magic,1610612753,49,26,23,0.531,2367.0,110.1,109.1,0.9,...,8,24,4,13,27,8,3,9,25,19
19,Phoenix Suns,1610612756,49,28,21,0.571,2367.0,115.5,113.0,2.4,...,8,8,16,11,13,11,21,7,27,20
20,Boston Celtics,1610612738,49,37,12,0.755,2377.0,117.9,109.4,8.5,...,6,3,5,1,20,16,11,6,5,21
21,Cleveland Cavaliers,1610612739,46,30,16,0.652,2218.0,113.5,108.2,5.3,...,29,15,2,6,14,9,6,4,20,21
22,Brooklyn Nets,1610612751,47,19,28,0.404,2271.0,112.7,114.1,-1.5,...,25,17,18,21,17,5,14,14,8,23
23,Charlotte Hornets,1610612766,47,10,37,0.213,2266.0,107.7,119.0,-11.2,...,26,27,30,30,22,21,20,28,21,23
24,LA Clippers,1610612746,47,32,15,0.681,2261.0,118.2,111.0,7.2,...,28,2,9,3,15,10,23,11,10,25
25,Minnesota Timberwolves,1610612750,49,34,15,0.694,2362.0,112.6,106.2,6.4,...,10,18,1,4,11,22,2,3,28,26
26,New York Knicks,1610612752,49,32,17,0.653,2352.0,114.9,110.4,4.5,...,16,13,7,7,29,1,7,1,18,27
27,Miami Heat,1610612748,49,26,23,0.531,2357.0,111.3,111.8,-0.5,...,14,22,12,18,16,26,4,21,17,28
28,Denver Nuggets,1610612743,50,34,16,0.680,2400.0,115.5,112.2,3.3,...,3,7,13,10,2,6,17,8,9,29
29,Chicago Bulls,1610612741,49,23,26,0.469,2382.0,111.4,112.3,-0.9,...,5,21,14,19,26,18,13,19,6,30

In [22]:
from nba_api.stats.endpoints import teamgamelogs

# Query for games where the Celtics were playing
stat_team_game = teamgamelogs.TeamGameLogs(season_nullable= "2023-24")
# The first DataFrame of those returned is what we want.
stat_team_game = stat_team_game.get_data_frames()[0]
stat_team_game

,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,AVAILABLE_FLAG
0,2023-24,1610612760,OKC,Oklahoma City Thunder,0022300695,2024-02-02T00:00:00,OKC vs. CHA,W,48.0,44,...,240,1295,195,35,403,332,433,289,122,1
1,2023-24,1610612745,HOU,Houston Rockets,0022300692,2024-02-02T00:00:00,HOU vs. TOR,W,48.0,55,...,307,883,317,1049,641,745,854,83,46,1
2,2023-24,1610612763,MEM,Memphis Grizzlies,0022300693,2024-02-02T00:00:00,MEM vs. GSW,L,48.0,35,...,307,717,668,812,1179,745,992,1259,1318,1
3,2023-24,1610612766,CHA,Charlotte Hornets,0022300695,2024-02-02T00:00:00,CHA @ OKC,L,48.0,41,...,1135,717,59,812,1368,888,992,1088,1318,1
4,2023-24,1610612750,MIN,Minnesota Timberwolves,0022300694,2024-02-02T00:00:00,MIN vs. ORL,L,48.0,38,...,931,1124,485,608,403,745,992,1088,757,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1445,2023-24,1610612737,ATL,Atlanta Hawks,0022300063,2023-10-25T00:00:00,ATL @ CHA,L,48.0,39,...,931,449,59,1373,210,598,433,931,911,1
1446,2023-24,1610612756,PHX,Phoenix Suns,0022300062,2023-10-24T00:00:00,PHX @ GSW,W,48.0,42,...,1038,1295,1079,273,844,1019,234,1013,584,1
1447,2023-24,1610612747,LAL,Los Angeles Lakers,0022300061,2023-10-24T00:00:00,LAL @ DEN,L,48.0,41,...,1038,449,1079,812,844,460,1214,1053,1146,1
1448,2023-24,1610612744,GSW,Golden State Warriors,0022300062,2023-10-24T00:00:00,GSW vs. PHX,L,48.0,36,...,1351,298,111,416,1036,1132,320,1164,833,1
1449,2023-24,1610612743,DEN,Denver Nuggets,0022300061,2023-10-24T00:00:00,DEN vs. LAL,W,48.0,48,...,397,449,317,416,403,148,854,543,274,1

In [23]:
stat_team_game.columns

Index(['SEASON_YEAR', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS',
       'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK',
       'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK',
       'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK',
       'REB_RANK', 'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK',
       'PF_RANK', 'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK', 'AVAILABLE_FLAG'],
      dtype='object')